Repository hee-ha/hana-heritage-BE, pull requests merged in 2024-06, with the labels that each got.

#17 JWT 및 로그인 기능 구현
  build.gradle
  src/main/java/com/heeha/domain/auth/controller/AuthController.java
  src/main/java/com/heeha/domain/auth/dto/CustomerUserInfoDto.java
  src/main/java/com/heeha/domain/auth/dto/JwtToken.java
  src/main/java/com/heeha/domain/auth/dto/UserRequestDto.java
  src/main/java/com/heeha/domain/auth/filter/CustomerAuthenticationFilter.java
  src/main/java/com/heeha/domain/auth/filter/ExceptionHandlingFilter.java
  src/main/java/com/heeha/domain/auth/jwt/JwtTokenExtractor.java
  src/main/java/com/heeha/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/com/heeha/domain/auth/service/AuthService.java
  src/main/java/com/heeha/domain/customer/dto/SignUpRequest.java
  src/main/java/com/heeha/domain/customer/repository/CustomerRepository.java
  src/main/java/com/heeha/domain/depositsProduct/util/ProductUtil.java
  src/main/java/com/heeha/global/config/BaseResponseStatus.java
  src/main/java/com/heeha/global/config/JwtAuthorizationArgumentResolver.java
  src/main/java/com/heeha/global/config/RedisConfig.java
  src/main/java/com/heeha/global/config/SwaggerConfig.java
  src/main/resources/application-dev.yml
Labels: Feat🐯, 유저

#20 자동 이체 기능 구현
  build.gradle
  src/main/java/com/heeha/HanaHeritageBeApplication.java
  src/main/java/com/heeha/domain/account/controller/AccountController.java
  src/main/java/com/heeha/domain/account/dto/MakeTransactionDto.java
  src/main/java/com/heeha/domain/account/entity/Account.java
  src/main/java/com/heeha/domain/account/service/AccountService.java
  src/main/java/com/heeha/domain/autoTransfer/controller/AutoTransferController.java
  src/main/java/com/heeha/domain/autoTransfer/dto/CreateAutoTransferDto.java
  src/main/java/com/heeha/domain/autoTransfer/entity/AutoTransfer.java
  src/main/java/com/heeha/domain/autoTransfer/jihu/controller/AutoTransferController.java
  src/main/java/com/heeha/domain/autoTransfer/jihu/dto/AutoTransferReq.java
  src/main/java/com/heeha/domain/autoTransfer/jihu/service/AutoTransferService.java
  src/main/java/com/heeha/domain/autoTransfer/repository/AutoTransferRepository.java
  src/main/java/com/heeha/domain/autoTransfer/scheduler/AutoTransferScheduler.java
  src/main/java/com/heeha/domain/autoTransfer/service/AutoTransferService.java
  src/main/java/com/heeha/domain/history/dto/TransferHistoryDto.java
  src/main/java/com/heeha/domain/history/entity/History.java
  src/main/java/com/heeha/domain/history/service/HistoryService.java
  src/main/java/com/heeha/global/config/BaseResponseStatus.java
  src/main/resources/application-dev.yml
Labels: 이체, Feat🐯

#56 차트 데이터 및 자산 타입별 조회 API 구현 , property 엔터티 수정
  src/main/java/com/heeha/domain/property/controller/PropertyController.java
  src/main/java/com/heeha/domain/property/dto/PropertyResponse.java
  src/main/java/com/heeha/domain/property/entity/Property.java
  src/main/java/com/heeha/domain/property/repository/PropertyRepository.java
  src/main/java/com/heeha/domain/property/service/PropertyService.java
  src/main/java/com/heeha/global/config/BaseResponseStatus.java
Labels: Feat🐯, 유언대용신탁

#59 OCR 연결 API 개발
  src/main/java/com/heeha/domain/ocr/controller/OcrController.java
  src/main/java/com/heeha/global/config/BaseResponseStatus.java
  src/main/resources/application-dev.yml
Labels: Feat🐯

#68 상품 조회수 top3 확인 기능 추가 및 각 상품의 일별 조회수 확인 기능 추가
  src/main/java/com/heeha/domain/depositsProduct/controller/DepositsProductController.java
  src/main/java/com/heeha/domain/depositsProduct/dto/PreferenceInfo.java
  src/main/java/com/heeha/domain/depositsProduct/service/DepositsProductService.java
  src/main/java/com/heeha/global/aop/Preference.java
  src/main/java/com/heeha/global/aop/PreferenceAop.java
  src/main/java/com/heeha/global/config/RedisConfig.java
Labels: Feat🐯, 어드민

#69 자동이체 배치 스케줄러 적용
  src/main/java/com/heeha/domain/account/service/AccountService.java
  src/main/java/com/heeha/domain/autoTransfer/scheduler/AutoTransferScheduler.java
  src/main/java/com/heeha/domain/autoTransfer/service/AutoTransferService.java
  src/main/java/com/heeha/domain/ocr/controller/OcrController.java
  src/main/java/com/heeha/global/config/BaseResponseStatus.java
  src/main/java/com/heeha/global/job/AutoTransferJobConfig.java
  src/main/java/com/heeha/global/job/AutoTransferTasklet.java
  src/main/java/com/heeha/global/job/SettlementJobConfig.java
  src/main/java/com/heeha/global/scheduler/BatchScheduler.java
  src/main/resources/application-dev.yml
Labels: 이체, Chore🐷

#72 feat: 간단한 오류 수정
  src/main/java/com/heeha/domain/account/controller/AccountController.java
  src/main/java/com/heeha/domain/auth/filter/CustomerAuthenticationFilter.java
  src/main/java/com/heeha/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/com/heeha/domain/ocr/controller/OcrController.java
Labels: Bug🦊
